name = "xlab"
uuid = "fbc1b93a-9496-464e-8f06-2c503180c422"
authors = ["jjgomezcadenas <jjgomezcadenas@gmail.com> and contributors"]
version = "0.1.0"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
